### ISSUE TITLE
Cannot install JupyterHub dashboards

### ISSUE THREAD

**Issue by danielitit** [jupyterhub/grafana-dashboards#32]
Hi Guys,

I cannot install JupyterHub dashboard every time I'm trying to do that I'm getting following error:

```
Traceback (most recent call last):
  File "./deploy.py", line 171, in <module>
    main()
  File "./deploy.py", line 167, in main
    deploy_dashboard(dashboard, folder['id'], api)
  File "./deploy.py", line 86, in deploy_dashboard
    db = populate_template_variables(api, db)
  File "./deploy.py", line 135, in populate_template_variables
    prom_id = api(f'/datasources/id/{var["datasource"]}')['id']
  File "./deploy.py", line 26, in grafana_request
    with urlopen(req, data) as resp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by msghiorso** [comment]
Same problem for me.

**Comment by danielitit** [comment]
@msghiorso it is a stupid issue, my boss help me on that (python ninja) and it turns out that somewhere data source name is hardcoded and it is case sensitive I had **P**rometheus but this code is looking for **p**rometheus!
