### ISSUE TITLE
The `deploy.py` script fails with  -  `No such file or directory: 'jsonnet'`

### ISSUE THREAD

**Issue by dsclassen** [jupyterhub/grafana-dashboards#48]
I'm having trouble getting the `deploy.py` script to work.

I believe I have satisfied all of the Prerequisites.

```
grafana-dashboards$ ./deploy.py http://127.0.0.1:3000
Traceback (most recent call last):
  File "/home/me/projects/grafana-dashboards/./deploy.py", line 195, in <module>
    main()
  File "/home/me/projects/grafana-dashboards/./deploy.py", line 191, in main
    deploy_dashboard(dashboard, folder['id'], api)
  File "/home/me/projects/grafana-dashboards/./deploy.py", line 92, in deploy_dashboard
    db = build_dashboard(dashboard_path, api, global_dash)
  File "/home/me/projects/grafana-dashboards/./deploy.py", line 53, in build_dashboard
    return json.loads(subprocess.check_output(
  File "/home/me/.conda/envs/py310/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/me/.conda/envs/py310/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/me/.conda/envs/py310/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/me/.conda/envs/py310/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'jsonnet'
```

This is my conda env:

```
$ conda list
# packages in environment at /home/me/.conda/envs/py310:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2022.10.11           h06a4308_0  
certifi                   2022.9.24       py310h06a4308_0  
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.0.4           py310h06a4308_0  
dataclasses               0.8                pyh6d0b6a4_7  
flask                     2.1.3           py310h06a4308_0  
flask-login               0.6.1                    pypi_0    pypi
flask-sqlalchemy          2.5.1                    pypi_0    pypi
greenlet                  1.1.2                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
itsdangerous              2.0.1                    pypi_0    pypi
jinja2                    3.1.2           py310h06a4308_0  
jsonnet                   0.19.1                   pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.0.3                h7f8727e_2  
markupsafe                2.1.1           py310h7f8727e_0  
ncurses                   6.3                  h5eee18b_3  
openssl                   1.1.1q               h7f8727e_0  
pip                       22.2.2          py310h06a4308_0  
python                    3.10.6               haa1d7c7_1  
rauth                     0.7.3                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.28.0                   pypi_0    pypi
setuptools                65.5.0          py310h06a4308_0  
sqlalchemy                1.4.37                   pypi_0    pypi
sqlite                    3.39.3               h5082296_0  
tk                        8.6.12               h1ccaba5_0  
tzdata                    2022e                h04d1e81_0  
urllib3                   1.26.9                   pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.37.1                   pypi_0    pypi
xz                        5.2.6                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0  
```

It seems to have partially worked? I see this in the Grafana admin panel.

<img width="1467" alt="Screen Shot 2022-10-31 at 2 31 50 PM" src="https://user-images.githubusercontent.com/8882563/199114492-bc11b94f-a530-4ad4-aec7-bd557e204207.png">

**Comment by yuvipanda** [comment]
@dsclassen do you have `jsonnet` installed? Does the command execute if you run it locally?

**Comment by BigFlagBurito** [comment]
I have the same problem.
I have installed jsonnet via pip as well as via git clone with make.
The error still appears.
Does jsonnet have to be in a specific directory?

**Comment by consideRatio** [comment]
Closing this and opening #112 with a concrete action point on failing loudly if `jsonnet` isn't available on Path
