### ISSUE TITLE
`deploy.py` doesn't allow to skip TLS verification for the Grafana certificate

### ISSUE THREAD

**Issue by itaytalmi** [jupyterhub/grafana-dashboards#73]
### Bug description

`deploy.py` fails when Grafana uses a self-signed/non-public certificate and it is not possible to skip TLS verification.

#### Expected behaviour

The script should be able to skip TLS verification for Grafana certificate, either hardcoded at the script level or via a flag passed to it.

#### Actual behaviour

```
./deploy.py "$GRAFANA_URL"
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/k8s/git/jupyterhub-observability/grafana-dashboards/./deploy.py", line 195, in <module>
    main()
  File "/home/k8s/git/jupyterhub-observability/grafana-dashboards/./deploy.py", line 188, in main
    folder = ensure_folder(args.folder_name, args.folder_uid, api)
  File "/home/k8s/git/jupyterhub-observability/grafana-dashboards/./deploy.py", line 32, in ensure_folder
    return api(f'/folders/{uid}')
  File "/home/k8s/git/jupyterhub-observability/grafana-dashboards/./deploy.py", line 26, in grafana_request
    with urlopen(req, data) as resp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

### How to reproduce

Just run the script as you normally would, on a Grafana instance that is configured with a self-signed certificate.

### Your personal set up

My Grafana instance uses a self-signed/private CA-signed certificate and exposed via Kubernetes ingress (the Kubernetes/ingress part doesn't really matter, it would fail on any Grafana with a non-public certificate...).

 - OS:
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by itaytalmi** [comment]
@yuvipanda Created the PR.
#74
